### ISSUE TITLE
ERROR [13/14] RUN flutter build web  

### ISSUE THREAD

**Issue by utasteam** [JErazo7/flutter-crypto-wallet#5]
=> ERROR [13/14] RUN flutter build web                                                                                                                                                                                    19.5s 
------
 > [13/14] RUN flutter build web:
#17 0.476    Woah! You appear to be trying to run flutter as root.
#17 0.476    We strongly recommend running the flutter tool without superuser privileges.
#17 0.477   /
#17 0.477 📎
#17 0.991 Downloading Web SDK...                                              4.9s
#17 7.073 Downloading CanvasKit...                                         1,279ms
#17 8.793
#17 8.794 💪 Building with sound null safety 💪
#17 8.794
#17 8.856 Compiling lib/main.dart for the Web...
#17 18.96 Target dart2js failed: Exception: Warning: The 'dart2js' entrypoint script is deprecated, please use 'dart compile js' instead.
#17 18.96 /root/.pub-cache/hosted/pub.dartlang.org/auto_route-2.4.2/lib/src/router/provider/auto_route_information_provider.dart:28:8:
#17 18.96 Error: The method 'AutoRouteInformationProvider.routerReportsNewRouteInformation' doesn't have the named parameter 'type' of overridden method 'RouteInformationProvider.routerReportsNewRouteInformation'.
#17 18.96   void routerReportsNewRouteInformation(RouteInformation routeInformation,
#17 18.96        ^
#17 18.96 ../../flutter/packages/flutter/lib/src/widgets/router.dart:1329:8:
#17 18.96 Info: This is the overridden method ('routerReportsNewRouteInformation').
#17 18.96   void routerReportsNewRouteInformation(RouteInformation routeInformation, {RouteInformationReportingType type = RouteInformationReportingType.none}) {}
#17 18.96        ^
#17 18.96 /root/.pub-cache/hosted/pub.dartlang.org/flutter_screenutil-5.0.0+2/lib/screen_util.dart:42:33:
#17 18.96 Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
#17 18.96  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
#17 18.96     var window = WidgetsBinding.instance?.window ?? ui.window;
#17 18.96                                 ^
#17 18.96 lib/presentation/routes/router.gr.dart:23:9:
#17 18.96 Error: No named parameter with the name 'builder'.
#17 18.96         builder: (data) {
#17 18.96         ^^^^^^^
#17 18.96 /root/.pub-cache/hosted/pub.dartlang.org/auto_route-2.4.2/lib/src/router/auto_route_page.dart:64:3:
#17 18.96 Info: Found this candidate, but the arguments don't match.
#17 18.96   MaterialPageX({
#17 18.96   ^^^^^^^^^^^^^
#17 18.96 lib/presentation/routes/router.gr.dart:30:9:
#17 18.96 Error: No named parameter with the name 'builder'.
#17 18.96         builder: (data) {
#17 18.96         ^^^^^^^
#17 18.96 /root/.pub-cache/hosted/pub.dartlang.org/auto_route-2.4.2/lib/src/router/auto_route_page.dart:64:3:
#17 18.96 Info: Found this candidate, but the arguments don't match.
#17 18.96   MaterialPageX({
#17 18.96   ^^^^^^^^^^^^^
#17 18.96 lib/presentation/routes/router.gr.dart:37:9:
#17 18.96 Error: No named parameter with the name 'builder'.
#17 18.96         builder: (_) {
#17 18.96         ^^^^^^^
#17 18.96 /root/.pub-cache/hosted/pub.dartlang.org/auto_route-2.4.2/lib/src/router/auto_route_page.dart:64:3:
#17 18.96 Info: Found this candidate, but the arguments don't match.
#17 18.96   MaterialPageX({
#17 18.96   ^^^^^^^^^^^^^
#17 18.96 lib/presentation/routes/router.gr.dart:42:9:
#17 18.96 Error: No named parameter with the name 'builder'.
#17 18.96         builder: (_) {
#17 18.96         ^^^^^^^
#17 18.96 /root/.pub-cache/hosted/pub.dartlang.org/auto_route-2.4.2/lib/src/router/auto_route_page.dart:64:3:
#17 18.96 Info: Found this candidate, but the arguments don't match.
#17 18.96   MaterialPageX({
#17 18.96   ^^^^^^^^^^^^^
#17 18.96 /root/.pub-cache/hosted/pub.dartlang.org/auto_route-2.4.2/lib/src/router/widgets/auto_tabs_router.dart:180:22:
#17 18.96 Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
#17 18.96  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
#17 18.96       WidgetsBinding.instance?.addPostFrameCallback((_) {
#17 18.96                      ^
#17 18.96 /root/.pub-cache/hosted/pub.dartlang.org/auto_route-2.4.2/lib/src/router/provider/auto_route_information_provider.dart:19:36:
#17 18.96 Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
#17 18.96  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
#17 18.96           location: WidgetsBinding.instance?.window.defaultRouteName ??
#17 18.96                                    ^
#17 18.96 /root/.pub-cache/hosted/pub.dartlang.org/auto_route-2.4.2/lib/src/router/provider/auto_route_information_provider.dart:55:39:
#17 18.96 Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
#17 18.96  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
#17 18.96     if (!hasListeners) WidgetsBinding.instance!.addObserver(this);
#17 18.96                                       ^
#17 18.96 /root/.pub-cache/hosted/pub.dartlang.org/auto_route-2.4.2/lib/src/router/provider/auto_route_information_provider.dart:62:39:
#17 18.96 Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
#17 18.96  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
#17 18.96     if (!hasListeners) WidgetsBinding.instance!.removeObserver(this);
#17 18.96                                       ^
#17 18.96 /root/.pub-cache/hosted/pub.dartlang.org/auto_route-2.4.2/lib/src/router/provider/auto_route_information_provider.dart:71:38:
#17 18.96 Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
#17 18.96  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
#17 18.96     if (hasListeners) WidgetsBinding.instance!.removeObserver(this);
#17 18.96                                      ^
#17 18.96 /root/.pub-cache/hosted/pub.dartlang.org/auto_route-2.4.2/lib/src/router/widgets/auto_route_navigator.dart:46:22:
#17 18.96 Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
#17 18.96  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
#17 18.96       WidgetsBinding.instance?.addPostFrameCallback((_) {
#17 18.96                      ^
#17 18.96 Error: Compilation failed.
#17 18.96
#17 18.96 Compiling lib/main.dart for the Web...                             10.1s
#17 18.96 Exception: Failed to compile application for the Web.
------
executor failed running [/bin/sh -c flutter build web]: exit code: 1
ERROR: Service 'crypto-wallet' failed to build : Build failed #

**Comment by utasteam** [comment]
someone help me pls.
here is flutter doctor
```
[√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.22000.493], locale vi-VN)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Android Studio
[√] VS Code (version 1.64.2)
[√] Connected device (2 available)
```
here is problems
![image](https://user-images.githubusercontent.com/38496223/155512664-7d5eaae7-a9f9-4999-8ac2-f7a4a5c77425.png)
